In [ ]:
import pandas as pd

# pip install tiingo
from tiingo import TiingoClient

In [ ]:
# prepare api key
config = {}

# create a configuration dictionary to store api key
config['api_key'] = 'xxxxxxxxxxxxxxxxxxxxxxxxxxx'

In [ ]:
# include a session key to enable reuse of the same HTTP Session for all api calls
config['session'] = True

# Initialize TiingoClient object instance with session and api keys
client = TiingoClient(config)

In [4]:
Results=client.get_ticker_price("MSFT",fmt='json',
                                     startDate='2021-07-01',
                                     endDate='2021-07-27',
                                     frequency='daily')

In [9]:
Results

[{'date': '2021-07-01T00:00:00.000Z',
  'close': 271.6,
  'high': 271.84,
  'low': 269.6,
  'open': 269.61,
  'volume': 16725323,
  'adjClose': 271.6,
  'adjHigh': 271.84,
  'adjLow': 269.6,
  'adjOpen': 269.61,
  'adjVolume': 16725323,
  'divCash': 0.0,
  'splitFactor': 1.0},
 {'date': '2021-07-02T00:00:00.000Z',
  'close': 277.65,
  'high': 278.0,
  'low': 272.5,
  'open': 272.82,
  'volume': 26474408,
  'adjClose': 277.65,
  'adjHigh': 278.0,
  'adjLow': 272.5,
  'adjOpen': 272.82,
  'adjVolume': 26474408,
  'divCash': 0.0,
  'splitFactor': 1.0},
 {'date': '2021-07-06T00:00:00.000Z',
  'close': 277.66,
  'high': 279.3698,
  'low': 274.3,
  'open': 278.03,
  'volume': 31565560,
  'adjClose': 277.66,
  'adjHigh': 279.3698,
  'adjLow': 274.3,
  'adjOpen': 278.03,
  'adjVolume': 31565560,
  'divCash': 0.0,
  'splitFactor': 1.0},
 {'date': '2021-07-07T00:00:00.000Z',
  'close': 279.93,
  'high': 280.6945,
  'low': 277.15,
  'open': 279.4,
  'volume': 23260031,
  'adjClose': 279.93,
  'adjHigh': 280.6945,
  'adjLow': 277.15,
  'adjOpen': 279.4,
  'adjVolume': 23260031,
  'divCash': 0.0,
  'splitFactor': 1.0},
 {'date': '2021-07-08T00:00:00.000Z',
  'close': 277.42,
  'high': 278.73,
  'low': 274.87,
  'open': 276.9,
  'volume': 24618591,
  'adjClose': 277.42,
  'adjHigh': 278.73,
  'adjLow': 274.87,
  'adjOpen': 276.9,
  'adjVolume': 24618591,
  'divCash': 0.0,
  'splitFactor': 1.0},
 {'date': '2021-07-09T00:00:00.000Z',
  'close': 277.94,
  'high': 278.05,
  'low': 275.32,
  'open': 275.72,
  'volume': 23916665,
  'adjClose': 277.94,
  'adjHigh': 278.05,
  'adjLow': 275.32,
  'adjOpen': 275.72,
  'adjVolume': 23916665,
  'divCash': 0.0,
  'splitFactor': 1.0},
 {'date': '2021-07-12T00:00:00.000Z',
  'close': 277.32,
  'high': 279.77,
  'low': 276.58,
  'open': 279.157,
  'volume': 18931695,
  'adjClose': 277.32,
  'adjHigh': 279.77,
  'adjLow': 276.58,
  'adjOpen': 279.157,
  'adjVolume': 18931695,
  'divCash': 0.0,
  'splitFactor': 1.0},
 {'date': '2021-07-13T00:00:00.000Z',
  'close': 280.98,
  'high': 282.8477,
  'low': 277.39,
  'open': 277.52,
  'volume': 26120128,
  'adjClose': 280.98,
  'adjHigh': 282.8477,
  'adjLow': 277.39,
  'adjOpen': 277.52,
  'adjVolume': 26120128,
  'divCash': 0.0,
  'splitFactor': 1.0},
 {'date': '2021-07-14T00:00:00.000Z',
  'close': 282.51,
  'high': 283.66,
  'low': 280.55,
  'open': 282.345,
  'volume': 23113662,
  'adjClose': 282.51,
  'adjHigh': 283.66,
  'adjLow': 280.55,
  'adjOpen': 282.345,
  'adjVolume': 23113662,
  'divCash': 0.0,
  'splitFactor': 1.0},
 {'date': '2021-07-15T00:00:00.000Z',
  'close': 281.03,
  'high': 282.51,
  'low': 279.83,
  'open': 282.0,
  'volume': 22604227,
  'adjClose': 281.03,
  'adjHigh': 282.51,
  'adjLow': 279.83,
  'adjOpen': 282.0,
  'adjVolume': 22604227,
  'divCash': 0.0,
  'splitFactor': 1.0},
 {'date': '2021-07-16T00:00:00.000Z',
  'close': 280.75,
  'high': 284.1,
  'low': 279.46,
  'open': 282.07,
  'volume': 26186848,
  'adjClose': 280.75,
  'adjHigh': 284.1,
  'adjLow': 279.46,
  'adjOpen': 282.07,
  'adjVolume': 26186848,
  'divCash': 0.0,
  'splitFactor': 1.0},
 {'date': '2021-07-19T00:00:00.000Z',
  'close': 277.01,
  'high': 280.37,
  'low': 274.45,
  'open': 278.9335,
  'volume': 32935634,
  'adjClose': 277.01,
  'adjHigh': 280.37,
  'adjLow': 274.45,
  'adjOpen': 278.9335,
  'adjVolume': 32935634,
  'divCash': 0.0,
  'splitFactor': 1.0},
 {'date': '2021-07-20T00:00:00.000Z',
  'close': 279.32,
  'high': 280.97,
  'low': 276.26,
  'open': 278.03,
  'volume': 26259741,
  'adjClose': 279.32,
  'adjHigh': 280.97,
  'adjLow': 276.26,
  'adjOpen': 278.03,
  'adjVolume': 26259741,
  'divCash': 0.0,
  'splitFactor': 1.0},
 {'date': '2021-07-21T00:00:00.000Z',
  'close': 281.4,
  'high': 281.52,
  'low': 277.29,
  'open': 278.905,
  'volume': 24364320,
  'adjClose': 281.4,
  'adjHigh': 281.52,
  'adjLow': 277.29,
  'adjOpen': 278.905,
  'adjVolume': 24364320,
  'divCash': 0.0,
  'splitFactor': 1.0},
 {'date': '2021-07-22T00:00:00.000Z',
  'close': 286.14,
  'high': 286.42,
  'low': 283.42,
  'open': 283.84,
  'volume': 23384059,
  'adjClose': 286.14,
  'adjHigh': 286.42,
  'adjLow': 283.42,
  'adjOpen': 283.84,
  'adjVolume': 23384059,
  'divCash': 0.0,
  'splitFactor': 1.0},
 {'date': '2021-07-23T00:00:00.000Z',
  'close': 289.67,
  'high': 289.99,
  'low': 286.5,
  'open': 287.37,
  'volume': 22768071,
  'adjClose': 289.67,
  'adjHigh': 289.99,
  'adjLow': 286.5,
  'adjOpen': 287.37,
  'adjVolume': 22768071,
  'divCash': 0.0,
  'splitFactor': 1.0},
 {'date': '2021-07-26T00:00:00.000Z',
  'close': 289.05,
  'high': 289.69,
  'low': 286.642,
  'open': 289.0,
  'volume': 23176073,
  'adjClose': 289.05,
  'adjHigh': 289.69,
  'adjLow': 286.642,
  'adjOpen': 289.0,
  'adjVolume': 23176073,
  'divCash': 0.0,
  'splitFactor': 1.0},
 {'date': '2021-07-27T00:00:00.000Z',
  'close': 286.54,
  'high': 289.575,
  'low': 282.95,
  'open': 289.43,
  'volume': 33604073,
  'adjClose': 286.54,
  'adjHigh': 289.575,
  'adjLow': 282.95,
  'adjOpen': 289.43,
  'adjVolume': 33604073,
  'divCash': 0.0,
  'splitFactor': 1.0}]

In [7]:
Stockdf = pd.DataFrame(Results)

In [8]:
Stockdf

,date,close,high,low,open,volume,adjClose,adjHigh,adjLow,adjOpen,adjVolume,divCash,splitFactor
0,2021-07-01T00:00:00.000Z,271.60,271.8400,269.600,269.6100,16725323,271.60,271.8400,269.600,269.6100,16725323,0.0,1.0
1,2021-07-02T00:00:00.000Z,277.65,278.0000,272.500,272.8200,26474408,277.65,278.0000,272.500,272.8200,26474408,0.0,1.0
2,2021-07-06T00:00:00.000Z,277.66,279.3698,274.300,278.0300,31565560,277.66,279.3698,274.300,278.0300,31565560,0.0,1.0
3,2021-07-07T00:00:00.000Z,279.93,280.6945,277.150,279.4000,23260031,279.93,280.6945,277.150,279.4000,23260031,0.0,1.0
4,2021-07-08T00:00:00.000Z,277.42,278.7300,274.870,276.9000,24618591,277.42,278.7300,274.870,276.9000,24618591,0.0,1.0
5,2021-07-09T00:00:00.000Z,277.94,278.0500,275.320,275.7200,23916665,277.94,278.0500,275.320,275.7200,23916665,0.0,1.0
6,2021-07-12T00:00:00.000Z,277.32,279.7700,276.580,279.1570,18931695,277.32,279.7700,276.580,279.1570,18931695,0.0,1.0
7,2021-07-13T00:00:00.000Z,280.98,282.8477,277.390,277.5200,26120128,280.98,282.8477,277.390,277.5200,26120128,0.0,1.0
8,2021-07-14T00:00:00.000Z,282.51,283.6600,280.550,282.3450,23113662,282.51,283.6600,280.550,282.3450,23113662,0.0,1.0
9,2021-07-15T00:00:00.000Z,281.03,282.5100,279.830,282.0000,22604227,281.03,282.5100,279.830,282.0000,22604227,0.0,1.0
10,2021-07-16T00:00:00.000Z,280.75,284.1000,279.460,282.0700,26186848,280.75,284.1000,279.460,282.0700,26186848,0.0,1.0
11,2021-07-19T00:00:00.000Z,277.01,280.3700,274.450,278.9335,32935634,277.01,280.3700,274.450,278.9335,32935634,0.0,1.0
12,2021-07-20T00:00:00.000Z,279.32,280.9700,276.260,278.0300,26259741,279.32,280.9700,276.260,278.0300,26259741,0.0,1.0
13,2021-07-21T00:00:00.000Z,281.40,281.5200,277.290,278.9050,24364320,281.40,281.5200,277.290,278.9050,24364320,0.0,1.0
14,2021-07-22T00:00:00.000Z,286.14,286.4200,283.420,283.8400,23384059,286.14,286.4200,283.420,283.8400,23384059,0.0,1.0
15,2021-07-23T00:00:00.000Z,289.67,289.9900,286.500,287.3700,22768071,289.67,289.9900,286.500,287.3700,22768071,0.0,1.0
16,2021-07-26T00:00:00.000Z,289.05,289.6900,286.642,289.0000,23176073,289.05,289.6900,286.642,289.0000,23176073,0.0,1.0
17,2021-07-27T00:00:00.000Z,286.54,289.5750,282.950,289.4300,33604073,286.54,289.5750,282.950,289.4300,33604073,0.0,1.0

In [10]:
df_filter = (Stockdf['close'] <= (Stockdf['open']))

In [11]:
Stockdf[df_filter]

,date,close,high,low,open,volume,adjClose,adjHigh,adjLow,adjOpen,adjVolume,divCash,splitFactor
2,2021-07-06T00:00:00.000Z,277.66,279.3698,274.30,278.0300,31565560,277.66,279.3698,274.30,278.0300,31565560,0.0,1.0
6,2021-07-12T00:00:00.000Z,277.32,279.7700,276.58,279.1570,18931695,277.32,279.7700,276.58,279.1570,18931695,0.0,1.0
9,2021-07-15T00:00:00.000Z,281.03,282.5100,279.83,282.0000,22604227,281.03,282.5100,279.83,282.0000,22604227,0.0,1.0
10,2021-07-16T00:00:00.000Z,280.75,284.1000,279.46,282.0700,26186848,280.75,284.1000,279.46,282.0700,26186848,0.0,1.0
11,2021-07-19T00:00:00.000Z,277.01,280.3700,274.45,278.9335,32935634,277.01,280.3700,274.45,278.9335,32935634,0.0,1.0
17,2021-07-27T00:00:00.000Z,286.54,289.5750,282.95,289.4300,33604073,286.54,289.5750,282.95,289.4300,33604073,0.0,1.0

In [13]:
Stockdf[(Stockdf['close'] == Stockdf['close'].max())].date

15    2021-07-23T00:00:00.000Z
Name: date, dtype: object

In [14]:
df_filter = (Stockdf['close'] > 280.00) & (Stockdf['volume'] > 26000000)

In [15]:
Stockdf[df_filter]

,date,close,high,low,open,volume,adjClose,adjHigh,adjLow,adjOpen,adjVolume,divCash,splitFactor
7,2021-07-13T00:00:00.000Z,280.98,282.8477,277.39,277.52,26120128,280.98,282.8477,277.39,277.52,26120128,0.0,1.0
10,2021-07-16T00:00:00.000Z,280.75,284.1000,279.46,282.07,26186848,280.75,284.1000,279.46,282.07,26186848,0.0,1.0
17,2021-07-27T00:00:00.000Z,286.54,289.5750,282.95,289.43,33604073,286.54,289.5750,282.95,289.43,33604073,0.0,1.0

In [16]:
Stockdf[df_filter].date

7     2021-07-13T00:00:00.000Z
10    2021-07-16T00:00:00.000Z
17    2021-07-27T00:00:00.000Z
Name: date, dtype: object

In [17]:
# get list of available stock tickers
tickers = client.list_stock_tickers()

In [19]:
type(tickers)

list

In [20]:
tkr = pd.DataFrame(tickers)

In [22]:
tkr.tail(20)

       ticker   exchange assetType priceCurrency   startDate     endDate
48159   ZXAIY       PINK     Stock           USD  2018-06-18  2021-07-27
48160  ZXYZ-A     NASDAQ     Stock           USD  2016-01-19  2021-07-27
48161   ZXZZT     NASDAQ     Stock           USD  2006-07-10  2021-07-27
48162      ZY     NASDAQ     Stock           USD  2021-04-22  2021-07-27
48163    ZYJT       PINK     Stock           USD  2014-07-01  2021-07-27
48164    ZYME       NYSE     Stock           USD  2017-04-28  2021-07-27
48165    ZYNE     NASDAQ     Stock           USD  2015-08-05  2021-07-27
48166    ZYQG       PINK     Stock           USD  2018-03-26  2021-07-27
48167    ZYRX       PINK     Stock           USD  2007-07-13  2021-07-27
48168    ZYTO       PINK     Stock           USD  2010-01-04  2018-05-01
48169    ZYXI     NASDAQ     Stock           USD  2002-12-31  2021-07-27
48170      ZZ       NYSE     Stock           USD
48171   ZZCLF       PINK     Stock           USD
48172   ZZHGF       PINK     Stock           USD  2017-12-28  2021-07-27
48173   ZZHGY       PINK     Stock           USD  2021-03-31  2021-07-27
48174     ZZK  NYSE ARCA     Stock           USD  2020-07-22  2021-07-27
48175    ZZLL      OTCQB     Stock           USD  2017-09-26  2021-07-27
48176   ZZLLD      OTCBB     Stock           USD  2017-10-06  2017-10-30
48177     ZZZ  NYSE ARCA     Stock           USD  2014-10-31  2021-07-27
48178   ZZZOF       PINK     Stock           USD  2017-09-22  2021-07-27